// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWgZOWx3W4Agal-maYsnYo2VgXkTKPlBs',
    appId: '1:760839039569:web:f0b09162c65abae0336670',
    messagingSenderId: '760839039569',
    projectId: 'sidgsitapp-e49ad',
    authDomain: 'sidgsitapp-e49ad.firebaseapp.com',
    storageBucket: 'sidgsitapp-e49ad.appspot.com',
    measurementId: 'G-BE60Q0XBEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG2u-1c6PsVL_ek6kZoTp6xR-mg4NoQRQ',
    appId: '1:760839039569:android:5d778b3cb7830bdc336670',
    messagingSenderId: '760839039569',
    projectId: 'sidgsitapp-e49ad',
    storageBucket: 'sidgsitapp-e49ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfz01F-7O3huPIbqrvYzc_2KipSwv-2pE',
    appId: '1:760839039569:ios:830649121cbb4964336670',
    messagingSenderId: '760839039569',
    projectId: 'sidgsitapp-e49ad',
    storageBucket: 'sidgsitapp-e49ad.appspot.com',
    iosClientId: '760839039569-ogkti23k32edialovb04j3ntd4q0a8ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.sidgsItApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfz01F-7O3huPIbqrvYzc_2KipSwv-2pE',
    appId: '1:760839039569:ios:830649121cbb4964336670',
    messagingSenderId: '760839039569',
    projectId: 'sidgsitapp-e49ad',
    storageBucket: 'sidgsitapp-e49ad.appspot.com',
    iosClientId: '760839039569-ogkti23k32edialovb04j3ntd4q0a8ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.sidgsItApp',
  );
}
